### ISSUE TITLE
Error in plugin

### ISSUE THREAD

**Issue by TSM-EVO** [nymann/Craftie#1]
Getting this error when loading the 1.0 version of this plugin. POEHUD is updated.
```

Log Entry : 10:42:20 AM Monday, 8 January 2018
 Method error: Render : System.IO.FileNotFoundException: Could not load file or assembly 'System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
File name: 'System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at Craftie.Core.Render()
   at PoeHUD.Plugins.BasePlugin.iRender()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
```

**Comment by nymann** [comment]
Arh, it's because you don't have the System.ValueTuple package it's included, in NET Framework 4.7 by default, I suspect others might not have that either, I'll copy the System.ValueTuple .dll locally with next release.
